version: "2"
plugins:
  structure:
    enabled: false
  duplication:
    enabled: false
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  gocyclo:
    enabled: true
    config:
      over: 5
exclude_patterns:
- vendor/
